name: Create PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Configure
        uses: actions/checkout@v2
        
      - name: Collect MD files
      - run: |
          mkdir output  # create output dir
          # this will also include README.md
          echo "FILELIST=$(printf '"%s" ' *.md)" >> $GITHUB_ENV
      
      - name: Convert MD files to PDF
        uses: docker://pandoc/latex:2.9
        with:
          args: --standalone --toc --resource-path=.:/data/Novation -V geometry:margin=2.5cm --number-sections --output=output/DrivenByMoss-Manual.pdf ${ env.FILELIST }
      
      - name: Publish result
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
